name: Security Checks

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:

  gitleaks:
    name: Gitleaks
    uses: ./.github/workflows/gitleaks.yml
    permissions:
      contents: read
      security-events: write

  sast:
    name: SAST
    needs: gitleaks
    uses: ./.github/workflows/sast.yml
    permissions:
      contents: read
      security-events: write
      actions: read
