name: Security Checks

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:

  secrets-scanning:
    name: Secrets Scanning
    uses: ./.github/workflows/secrets-scanning.yml
    permissions:
      contents: read
      security-events: write

  sast:
    name: SAST
    uses: ./.github/workflows/sast.yml
    permissions:
      contents: read
      actions: read
      security-events: write

  security-gate:
    name: Security Gate
    needs:
      - secrets-scanning
      - sast

    if: always()

    uses: ./.github/workflows/security-gate.yml
    permissions:
      contents: read
      actions: read
