name: Security Checks

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    name: Gitleaks
    uses: ./.github/workflows/gitleaks.yml

  sast:
    name: SAST
    needs: gitleaks
    uses: ./.github/workflows/sast.yml
