name: SAST

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:

  CodeQL:
    name: CodeQL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript-typescript
          queries: security-extended

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
        with:
          category: "/language:javascript-typescript"


  Semgrep:
    name: Semgrep
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run Semgrep
        run: |
          semgrep scan \
            --config p/default \
            --config p/security-audit \
            --config p/owasp-top-ten \
            --sarif \
            --output semgrep.sarif 

      - name: Upload Semgrep SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep.sarif
          category: semgrep

      - name: Upload Semgrep Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep.sarif
